// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/truvornex-v1/ArcLinear.tsx": () => import("../components/mockups/truvornex-v1/ArcLinear.tsx"),
  "./components/mockups/truvornex-v2/AppleWhitespace.tsx": () => import("../components/mockups/truvornex-v2/AppleWhitespace.tsx"),
  "./components/mockups/truvornex-v3/Editorial.tsx": () => import("../components/mockups/truvornex-v3/Editorial.tsx")
};
